"""create team table

Revision ID: 06bf558207ab
Revises: d12c0b8b0663
Create Date: 2025-02-09 12:20:44.456216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bf558207ab'
down_revision: Union[str, None] = 'd12c0b8b0663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('DELETED', 'ACTIVE', name='teamstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_name', 'teams', ['name'], unique=False)
    op.create_index('idx_team_tenant_id', 'teams', ['tenant_id'], unique=False)
    op.create_index('idx_team_workspace_id', 'teams', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_team_workspace_id', table_name='teams')
    op.drop_index('idx_team_tenant_id', table_name='teams')
    op.drop_index('idx_team_name', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
