"""create tenant table

Revision ID: 2ac23d66c8c9
Revises: 
Create Date: 2025-02-09 12:09:11.779488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac23d66c8c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('company_logo', sa.String(length=512), nullable=True),
    sa.Column('company_size', sa.String(length=255), nullable=True),
    sa.Column('company_location', sa.Text(), nullable=False),
    sa.Column('industry_type', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('primary_language', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('time_format', sa.String(length=50), nullable=False),
    sa.Column('time_zone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('enable_two_factor', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DELETED', 'ACTIVE', 'IN_ACTIVE', 'NOT_VERIFIED', name='tenantstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_company_name', 'tenants', ['company_name'], unique=False)
    op.create_index('idx_tenant_domain', 'tenants', ['domain'], unique=False)
    op.create_index('idx_tenant_status', 'tenants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tenant_status', table_name='tenants')
    op.drop_index('idx_tenant_domain', table_name='tenants')
    op.drop_index('idx_tenant_company_name', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
